[package]
name = "brittonfischer/replicaservice"
description = "ReplicaService is a selective state replication system. Ported from madstudioroblox/replicaservice"
version = "0.1.0"
license = "Apache-2.0"
authors = ["loleris", "Scarious"]
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"
exclude = ["test", "test.project.json", "DevPackages"]

[dependencies]